### Assignment No. 6

### Name : Jawale Kishor Macchindra
### Roll no. : EN23107052
### Batch : C

In [13]:
import pandas as pd
import numpy as np
import re
import nltk

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\abhij\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\abhij\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
df = pd.read_csv("SMSSpamCollection", sep='\t', names=["label","message"])
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
def preprocess(text):
    
    # lowercase
    text = text.lower()
    
    # remove special characters
    text = re.sub('[^a-zA-Z]', ' ', text)
    
    # tokenization
    words = text.split()
    
    # stopword removal + lemmatization
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    
    return " ".join(words)

df['clean_message'] = df['message'].apply(preprocess)
df.head()

,label,message,clean_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts st ...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah think go usf life around though

In [4]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['clean_message'])
y = df['label'].map({'ham':0,'spam':1})

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [9]:
y_pred = model.predict(X_test)

In [10]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.9713004484304932
Precision: 0.9915966386554622
Recall   : 0.7919463087248322
F1 Score : 0.8805970149253731

In [11]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print(cm)

Confusion Matrix
[[965   1]
 [ 31 118]]

In [15]:
def predict_spam(message):
    
    message = preprocess(message)
    vector = vectorizer.transform([message])
    prediction = model.predict(vector)[0]
    if prediction == 1:
        return "Spam"
    else:
        return "Ham"

print(predict_spam("WIN a free iPhone now click here"))
print(predict_spam("Lunch tomorrow?"))
print(predict_spam("URGENT update your bank account"))

Spam
Ham
Ham